version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.21.4
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=$GITEA_USER_UID
      - USER_GID=$GITEA_USER_GID
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=$DB_HOST
      - GITEA__database__NAME=$DB_NAME
      - GITEA__database__USER=$DB_USER
      - GITEA__database__PASSWD=$DB_PASSWD
    restart: always
    networks:
      - gitea
    volumes:
      - $VOLUM_GITEA:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "$GITEA_PORT_SERVE:3000"
      - "$GITEA_PORT_SSH:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWD
      - POSTGRES_DB=$DB_NAME
    networks:
      - gitea
    volumes:
      - $VOLUM_DB:/var/lib/postgresql/data